only look in `src` for `bun test`
Previously, `yarn run test:bun` would fail if we already built for `deno`, since it does not respect the filter in `jest.config.json`, failing with errors like:
```
deno/lib/__tests__/record.test.ts:
error: FileNotFound reading "https://deno.land/x/expect@v0.2.6/mod.ts"
```